on:
  schedule:
    - cron: "13 * * * *"
  workflow_dispatch:

name: Fetch data

jobs:
  james_river_watch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CSO_TOKEN: ${{ secrets.CSO_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        
      - name: jet up Python
        uses: actions/setup-python@v6

      - name: Set up Python packages
        run: pip install esridump
        
      - name: Poll James River Watch ArcGIS APi
        run: ./james_river_watch.sh

      - name: Commit record to repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/james_river_watch data/james_river_watch.geojson
          git commit -m "[auto] Pull James River Watch data $(TZ=America/New_York date +'%Y-%m-%d %H:%M')"
          git push
  combined_sewer_overflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CSO_TOKEN: ${{ secrets.CSO_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        
      - name: Set up R
        uses: eddelbuettel/github-actions/r2u-setup@master

      - name: Set up R packages
        run: |
         Rscript -e "install.packages(c('httr2', 'dplyr', 'sf', 'jsonlite'))"
        
      - name: Poll CSO API
        run: |
          Rscript -e "source('rva_cso.R')"

      - name: Commit record to repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "data/cso_overflow.geojson" "data/cso_log.csv"
          git commit -m "[auto] Pull CSOs $(TZ=America/New_York date +'%Y-%m-%d %H:%M')"
          git push
